## Repository labels managed by github-labeler

# Type labels
- name: "type: feature"
  color: "a2eeef"
  description: "New feature or request"
- name: "type: fix"
  color: "d73a4a"
  description: "Bug fix or quality improvement"
- name: "type: docs"
  color: "0075ca"
  description: "Documentation changes"
- name: "type: chore"
  color: "cfd3d7"
  description: "Tooling, infra, or maintenance"
- name: "type: ci"
  color: "5319e7"
  description: "Continuous integration / workflow"

# Scope labels
- name: "scope: ontology"
  color: "0e8a16"
  description: "Core ODIM-MH ontology (OWL/TBox)"
- name: "scope: vocab"
  color: "1d76db"
  description: "SKOS vocabularies"
- name: "scope: queries"
  color: "5319e7"
  description: "SPARQL queries and validators"
- name: "scope: tooling"
  color: "d4c5f9"
  description: "Tooling and Docker wrappers"
- name: "scope: docs"
  color: "0e8a16"
  description: "Documentation and website"
- name: "scope: gh-setup"
  color: "fbca04"
  description: "GitHub settings and repo hygiene"

# Status labels
- name: "status: needs triage"
  color: "d4c5f9"
  description: "Awaiting review/triage"
- name: "status: in progress"
  color: "0e8a16"
  description: "Actively being worked on"
- name: "status: blocked"
  color: "b60205"
  description: "Blocked by dependency or decision"
- name: "status: ready for review"
  color: "5319e7"
  description: "PR review requested"

