PREFIX odim:    <http://connectdigitalstudy.com/ontology#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov:    <http://www.w3.org/ns/prov#>

ASK {
  VALUES (?p ?super) {
    (odim:wasComputedBy       prov:wasGeneratedBy)
    (odim:wasGeneratedBy      prov:wasGeneratedBy)
    (odim:wasDerivedFrom      prov:wasDerivedFrom)
    (odim:usedDevice          prov:used)
    (odim:usedAppInterface    prov:used)
    (odim:usedDataInterface   prov:used)
    (odim:wasCollectedFrom    prov:wasAttributedTo)
    (odim:wasAttributedTo     prov:wasAttributedTo)
    (odim:associatedWithDevice prov:wasAssociatedWith)
  }
  ?p rdfs:subPropertyOf ?super .
}
