PREFIX odim:    <http://connectdigitalstudy.com/ontology#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov:    <http://www.w3.org/ns/prov#>

ASK {
  VALUES (?c ?super) {
    (odim:Computation         prov:Activity)
    (odim:SensingActivity     prov:Activity)
    (odim:DataTransferEvent   prov:Activity)
    (odim:NotificationEvent   prov:Activity)
    (odim:Measurement         prov:Entity)
    (odim:Feature             prov:Entity)
    (odim:DerivedFeature      prov:Entity)
    (odim:DataSet             prov:Entity)
    (odim:DigitalPhenotype    prov:Entity)
    (odim:Participant         prov:Agent)
    (odim:Device              prov:Agent)
  }
  ?c rdfs:subClassOf ?super .
}
