PREFIX odim:    <http://connectdigitalstudy.com/ontology#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>

# All odim:skosTag objects are SKOS Concepts that are in some scheme
ASK {
  FILTER NOT EXISTS {
    ?s odim:skosTag ?c .
    FILTER NOT EXISTS { ?c a skos:Concept ; skos:inScheme ?scheme }
  }
}
