PREFIX connect: <http://connectdigitalstudy.com/ontology#>
PREFIX sosa:    <http://www.w3.org/ns/sosa/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>

ASK {
  # Class mapping exists
  connect:Measurement rdfs:subClassOf sosa:Observation .

  # Property mappings exist (via subPropertyOf on convenience props)
  connect:observedProperty rdfs:subPropertyOf sosa:observedProperty .
  connect:featureOfInterest rdfs:subPropertyOf sosa:hasFeatureOfInterest .

  # Examples have observedProperty and FOI
  connect:HeartRateMeasurementX connect:observedProperty connect:HeartRate ;
                                 connect:featureOfInterest connect:ParticipantX .
  connect:HeartRateVariabilityMeasurementX connect:observedProperty connect:HeartRateVariability ;
                                           connect:featureOfInterest connect:ParticipantX .
  connect:ActivityMeasurementX connect:observedProperty connect:ActivityDuration ;
                               connect:featureOfInterest connect:ParticipantX .
  connect:SleepStageMeasurementX connect:observedProperty connect:SleepDuration ;
                                 connect:featureOfInterest connect:ParticipantX .
}

