PREFIX odim:    <http://connectdigitalstudy.com/ontology#>

ASK {
  odim:HeartRateMeasurementX odim:resultTime ?t1 .
  odim:HeartRateVariabilityMeasurementX odim:resultTime ?t2 .
  odim:ActivityMeasurementX odim:resultTime ?t3 .
  odim:SleepStageMeasurementX odim:resultTime ?t4 .
}
